//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsianOptionsFSharp.AsianOptionsServiceFSharp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsianOptionsServiceFSharp.IAsianOptionsServiceFSharp")]
    public interface IAsianOptionsServiceFSharp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsianOptionsServiceFSharp/PAO", ReplyAction="http://tempuri.org/IAsianOptionsServiceFSharp/PAOResponse")]
        double PAO(double initial, double exercise, double up, double down, double interest, int periods, int runs);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAsianOptionsServiceFSharp/PAO", ReplyAction="http://tempuri.org/IAsianOptionsServiceFSharp/PAOResponse")]
        System.IAsyncResult BeginPAO(double initial, double exercise, double up, double down, double interest, int periods, int runs, System.AsyncCallback callback, object asyncState);
        
        double EndPAO(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsianOptionsServiceFSharpChannel : AsianOptionsFSharp.AsianOptionsServiceFSharp.IAsianOptionsServiceFSharp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PAOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PAOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsianOptionsServiceFSharpClient : System.ServiceModel.ClientBase<AsianOptionsFSharp.AsianOptionsServiceFSharp.IAsianOptionsServiceFSharp>, AsianOptionsFSharp.AsianOptionsServiceFSharp.IAsianOptionsServiceFSharp {
        
        private BeginOperationDelegate onBeginPAODelegate;
        
        private EndOperationDelegate onEndPAODelegate;
        
        private System.Threading.SendOrPostCallback onPAOCompletedDelegate;
        
        public AsianOptionsServiceFSharpClient() {
        }
        
        public AsianOptionsServiceFSharpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsianOptionsServiceFSharpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsianOptionsServiceFSharpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsianOptionsServiceFSharpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<PAOCompletedEventArgs> PAOCompleted;
        
        public double PAO(double initial, double exercise, double up, double down, double interest, int periods, int runs) {
            return base.Channel.PAO(initial, exercise, up, down, interest, periods, runs);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPAO(double initial, double exercise, double up, double down, double interest, int periods, int runs, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPAO(initial, exercise, up, down, interest, periods, runs, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public double EndPAO(System.IAsyncResult result) {
            return base.Channel.EndPAO(result);
        }
        
        private System.IAsyncResult OnBeginPAO(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double initial = ((double)(inValues[0]));
            double exercise = ((double)(inValues[1]));
            double up = ((double)(inValues[2]));
            double down = ((double)(inValues[3]));
            double interest = ((double)(inValues[4]));
            int periods = ((int)(inValues[5]));
            int runs = ((int)(inValues[6]));
            return this.BeginPAO(initial, exercise, up, down, interest, periods, runs, callback, asyncState);
        }
        
        private object[] OnEndPAO(System.IAsyncResult result) {
            double retVal = this.EndPAO(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPAOCompleted(object state) {
            if ((this.PAOCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PAOCompleted(this, new PAOCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PAOAsync(double initial, double exercise, double up, double down, double interest, int periods, int runs) {
            this.PAOAsync(initial, exercise, up, down, interest, periods, runs, null);
        }
        
        public void PAOAsync(double initial, double exercise, double up, double down, double interest, int periods, int runs, object userState) {
            if ((this.onBeginPAODelegate == null)) {
                this.onBeginPAODelegate = new BeginOperationDelegate(this.OnBeginPAO);
            }
            if ((this.onEndPAODelegate == null)) {
                this.onEndPAODelegate = new EndOperationDelegate(this.OnEndPAO);
            }
            if ((this.onPAOCompletedDelegate == null)) {
                this.onPAOCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPAOCompleted);
            }
            base.InvokeAsync(this.onBeginPAODelegate, new object[] {
                        initial,
                        exercise,
                        up,
                        down,
                        interest,
                        periods,
                        runs}, this.onEndPAODelegate, this.onPAOCompletedDelegate, userState);
        }
    }
}
